export LAB_LOCATION="italynorth"
export LAB_SUFFIX="e385bc0c"
export LAB_RG="rg-cea-ud02-e385bc0c"
export LAB_VNET="vnet-cea-ud02"
export LAB_SUBNET="snet-app"
export LAB_STORAGE="stceae385bc0c"
export LAB_DELETE_AFTER="$(date -d '+2 days' +%F)"